- binder/enum.cpp
The reasoning is that we are using the alternative values of the values in the generated code, not just the declaration
> enum include should also reference definition headers

- documentation/config.rst
- source/class.cpp
- source/config.cpp
- source/config.hpp
- test/T31.include_for_class.config
- test/T31.include_for_class.hpp
- test/T31.include_for_class.incl.a.include
- test/T31.include_for_class.incl.b.extra.include
- test/T31.include_for_class.incl.b.include
- test/T31.include_for_class.ref
Add support for per-class includes to binding generator.  Adding
"include_for_class" option to binder, which triggers inclusion of a
header on a class-specific basis. This features supports the definition
of per-class custom binding code in a standalone header, which may then
be referenced via the +binder option.
> Add support for per-class includes.

- documentation/config.rst
- source/config.cpp
- source/config.hpp
- source/function.cpp
- test/T32.call_guard.config
- test/T32.call_guard.hpp
- test/T32.call_guard.ref
- test/self-test.py
Adds additional binder configuration parameter allowing optional
specification of a default call guard. This call guard is applied to
all generated function invocations. Intended to support project-wide
application of gil_scoped_release in code bases in which all c++ code is
(a) gil-safe or (b) protects all python api access via gil state ensure.
Includes documentation, test, and configuration updates. Includes minor
update to test script to explictly specify python2.7 for test execution,
providing support for environments in which python is mapped to python3.
> Add support for call guards in function invocations.

- build.py
Update build.py to build from llvm source download, rather than git checkout.
This change significantly reduces the required disc space and checkout time for
a binder build by eliminating the full git clone of the llvm and clang.
Updates build invocation to *only* build binder, rather than the full
collection of clang and llvm tools, reducing the total build time.
> Build binder from llvm source download.

- examples/example_struct/config.cfg
- examples/example_struct/make_bindings_via_cmake.py
1) Make it easier to use cmake example script with other projects. All paths and settings are in the single place (in the top of the script)
2) Unify usage of quotes (to visually stress the difference from C\C++ I selected single quotes, however, it is not a problem to put all of them to be double quotes).  
3) Add other often used file extensions widely used in C++ projects.
4) In many projects they use separate include and source dir. I am not sure whether line "for include_dir in [binder_source, .." is OK now for Binder, as it includes both this_project_source and this_project_include (which are the same for example_structure project).
5) Added missing config file which is also needed for make_binding_via_bash_and_stl.sh
> Example cmake script

- source/config.hpp
Binder can be built with MSVC (I used VS 2017) with only a few minor tweaks. They are:
- Alias `uint` to `unsigned int`
- I'm not sure how in the include chain `uint` gets defined on Linux or Clang/gcc, but for MSVC it's undefined
- Include `<ciso646>`
- MSVC by default does not support the alternative operator representations (e.g. `or`, `and`). However, they can be added in by including `<ciso646>`
> Few tweaks to support building with MSVC

- documentation/config.rst
- source/binder.cpp
are not useful in generating bindings and you are sure that
the bindings are still correct and you want to suppress ugly
fatal errors then you can use --suppress-errors=true as argument
to get rid of them.
Sorry. This is the same as https://github.com/RosettaCommons/binder/pull/65
I had to rebranch stuff on my repo. So it closed the other PR.
> a way to suppress errors if the not-found included headers

- source/class.cpp
- source/function.cpp
Use variable names for overloaded constructors instead of a1, a2 ...
And more importantly add `pybind11::arg` to get proper helpers inside the python for overloaded constructors with arguments with default values.
> Use variable names as well for overloaded constructors

- examples/example_struct/make_bindings_via_cmake.py
- source/type.cpp
writing good documentation is hard and takes a lot of time, lets just push the core binder changes through in this PR while I wait until i have a spare moment or two to revisit the compiling documentation that I started on https://github.com/RosettaCommons/binder/pull/58/files
After looking through it, I'm not sure it's professional or thorough for the public documentation... (yet)
@kostyfisik track this, it should get merged quickly
> Danpf/uninitialized copy fix (binder fixes only)

- documentation/config.rst
Fixes the config example to refer to `binder_for_namespace` instead of `add_on_binder_for_namespace`.
> Fix binder_for_namespace docs

- documentation/install.rst
- source/CMakeLists.txt
Added PRIVATE keyword to libraries to remove error/warning 'all-keyword or all-plain' and fixed typo in docs.
> Very tiny fixes

- build.py
`curl` doesn't follow redirects, and releases.llvm.org has changed the HTTP URLs the script wants to use so that they 301 redirect to their HTTPS versions. That change breaks the script as it is; it needs to go directly to the HTTPS URLs for curl to work.
> Fix links to LLVM sources that have moved

- .github/workflows/fedora26/Dockerfile
- .github/workflows/fedora26/action.yaml
- .github/workflows/fedora26/entrypoint.sh
- .github/workflows/fedora27/Dockerfile
- .github/workflows/fedora27/action.yaml
- .github/workflows/fedora27/entrypoint.sh
- .github/workflows/fedora28/Dockerfile
- .github/workflows/fedora28/action.yaml
- .github/workflows/fedora28/entrypoint.sh
- .github/workflows/fedora29/Dockerfile
- .github/workflows/fedora29/action.yaml
- .github/workflows/fedora29/entrypoint.sh
- .github/workflows/fedora30/Dockerfile
- .github/workflows/fedora30/action.yaml
- .github/workflows/fedora30/entrypoint.sh
- .github/workflows/fedora31/Dockerfile
- .github/workflows/fedora31/action.yaml
- .github/workflows/fedora31/entrypoint.sh
- .github/workflows/fedora32/Dockerfile
- .github/workflows/fedora32/action.yaml
- .github/workflows/fedora32/entrypoint.sh
- .github/workflows/fedora33/Dockerfile
- .github/workflows/fedora33/action.yaml
- .github/workflows/fedora33/entrypoint.sh
- .github/workflows/main.yml
Hi @lyskov  ,
this MR implements CI for Linux.
Note:
- while the CI now attempts to run tests via cmake, the result of CI job is defined only with the result of the compilation.
That is why there is a third step in the CI.  Please note that the existing tests are not portable across compilers and platforms, so some logic should be added to the test suite before actually use the results of tests to define the outcome of the CI jobs. 
- CI runs on push/pull and every 5 days on cron. Af far as I remember this works only on master branch.
- Windows and mac can be added as well, but it makes sense to do that in another MR.
- A version with full rebuild can be added as well, but again it makes more sense to have a separate MR for that.
- There are many docker images from other distributions, so …
> Linux CI: fast version with external LLVM using Fedora 

- documentation/config.rst
From rich diff:
> ![image](https://user-images.githubusercontent.com/26719449/89111562-1d610f00-d425-11ea-8788-c17ec7bb5156.png)
> doc/config: Fix typo in default_call_guard URL

- documentation/install.rst
Currently, `llvm` and `clang` point to LLVM/Clang 6 :(
* Adds `llvm-dev` and fixes spelling for `libclang-dev`
* Adds example for CMake configuration on Ubuntu
> install: For Ubuntu 18.04+, recommend llvm-10 + clang-10

- documentation/config.rst
> doc/config: Use code formatting for flags

- documentation/install.rst
Hi @lyskov ,
this MR contains an update of documentation for usage of binder compiled with standalone LLVm in the case if clang is not a system compiler.
This is motivated by #119 
Best regards,
Andrii
> Extension of documentation: how to point binder to the desired headers

- test/T02.function.hpp
Eliminates difference in the code generated by binder  on different systems.
Closes #127
> Eliminates difference in the code generated by binder  on different systems

- test/T11.override.hpp
To match the reference source one should use 
```
#define  _GLIBCXX_USE_CXX11 0
```
this assures usage of  ``string`` instead of  `` _cxx11::string`` 
``<memory>`` header is not needed.
> Fixing another test to make it work exacly the same on multiple systems

- source/class.cpp
- source/class.hpp
If an `+include_for_class` directive is present in the config file for a nested class, it should be processed while processing the relevant includes for the parent.
**Note:** This uses the `for_public_nested_classes` function added in #125, so #125  should be merged before this PR.
> Add Includes for Nested Classes

- source/config.cpp
If the config file has Windows-style line endings (`\r\n`) and is read on Linux, things get a bit funky. This is because `std::getline` returns lines with a carriage return at the end when it encounters Windows-style endings on Linux (it treats the `\r` as any old character and adds it to the returned line).
An example of what's broke: directives to skip classes don't work because all the members of `Config::classes_to_skip` have a `\r` at the end, causing the lookup to always fail.
The simple, if inelegant, fix is to simply check to see if the last character of the result from `std::getline` is a carriage return, and if so pop it off.
> Fix Windows line endings in config file on Linux

- .clang-format
Hi @lyskov ,
here is an attempt to have a clang-format config that would match the observed formatting rules in the code (e.g. tabs).
If you find it reasonable, and  the `clang-format  -i source/*p` command  is executed on the reference platform once: 
- the need to check or adjust formatting in any merge request will disappear. 
- practically the formatting check can be integrated into CI. Again, no need for a manual check.
Also, the format file is not my personal preferences (don't have any), but an attempt to match the existing rules. The idea of this MR is just to have any formatting config so the code formatting can be done  (semi-)automatically.
Bets regards,
Andrii
P.S. I could not deduce the prefered style for the breaks before braces from the code. Sometimes it looks like …
> Added clang-format config (for consideration)

- documentation/basics.rst
- documentation/config.rst
- documentation/debugging.rst
- documentation/examples.rst
- documentation/install.rst
- documentation/testing.rst
Hi @lyskov ,
here are some fixes for docs.
Briefly I've fixed some indentation, spelling and tried to use more ``code-block::``. No changes to the text part from 
slightly more smooth description of the static build.
Best regards,
Andrii
> Checks of spelling and fixes in docs

- test/CMakeLists.txt
Hi @lyskov ,
here are fixes for CI
1)  To prevent some tests from running with old pybind11 (<2.6.0).
The pybind11 2.6.0 appeared just 2 days ago, so the fix literally prevents tests from running is the version is insufficient. 
In some weeks/days the latest Fedoras will be updated and all tests will be active again for it.
The fix will still make sense for older distros.
2) It seems the regenerated references differ from the previous version so the  difference tests are now set to always pass.
Best regards,
Andrii
Another, but more global question:   would you consider to tag a next version of binder?
> Fix tests pybind11 v2.6

- .github/workflows/main.yml
- .github/workflows/osx/entrypoint.sh
- documentation/install.rst
- source/CMakeLists.txt
- test/CMakeLists.txt
Hi @lyskov,
This PR:  
- Adds support for compilation with external LLVM on Mac.
- Adds CI for Mac. ( Only llvm 11).
- Adds a bit of docs on compilation with external LLVM on Mac.
Some tests are disabled on mac because I have an old one. These should work fine on  a newer version.    
Best regards,
Andrii
> Adding support for compilation with external LLVM on Mac

- source/context.cpp
Hi @lyskov ,
here is a tiny, completely non-urgent pull request.
The idea is to remove semicolons in "module_header" to prevent gcc warnings when compiling with -Wpedantic.
The messages I see look like this:
```
warning: extra ‘;’ [-Wpedantic]
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
^
warning: extra ‘;’ [-Wpedantic]
PYBIND11_DECLARE_HOLDER_TYPE(T, T*);
^
warning: extra ‘;’ [-Wpedantic]
PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>);
^
```
There are two other warnings:
```
warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
^
warning: ISO C++11 requires at least one argument for the "..." in a variadic macro
PYBIND11_DECLARE_HOLDER_TYPE(T, T*);
```
however these are inside the `pybind11` code. …
> Remove semicolons in module_header

- source/type.cpp
Add handling for bits/stl_uninitialized.h, which appeared in some generated sources.
According to gcc docs this header should be related to <memory>.
> Add handling for bits/stl_uninitialized.h

- source/class.hpp
- source/context.cpp
- source/context.hpp
- source/function.hpp
- source/type.hpp
- source/util.hpp
try to make sense of unclear comments;
uniformly use '///' for Doxygen function/class/namespace comments
> source: correct typos in function comments;

- source/binder.cpp
- source/config.cpp
- source/context.cpp
In particular, printing the .hpp input files that are to be processed is necessary to explain repetative output like
```
Generate bindings, pass 1...
```
> In terminal output, print input files we are processing

- source/type.cpp
As discussed in issue #192.
Demo code reported in that issue does compile and works correctly.
Still hoping for native, fast implementation though.
> add std::complex to python builtins

- source/CMakeLists.txt
- source/binder.cpp
- source/binder.hpp
- source/class.cpp
- source/class.hpp
- source/config.cpp
- source/context.cpp
- source/context.hpp
- source/function.hpp
- source/main.cpp
- source/options.cpp
- source/options.hpp
- source/type.cpp
- source/util.cpp
As proposed in https://github.com/RosettaCommons/binder/discussions/200.
This PR depends on the previous one, https://github.com/RosettaCommons/binder/pull/203; i.e. it is meant to be rebased on master after merger of #203.
> New source files main.cpp, options.hpp; move IncludeSet and Binder from context.hpp to binder.hpp

- source/type.cpp
- test/T60.pybind11.hpp
This PR labels pybind11 objects as builtins. For example `pybind11::dict` and `pybind11::list`.
> pybind11 bindings

- documentation/config.rst
- source/config.cpp
- source/options.cpp
- source/options.hpp
- source/type.cpp
- test/CMakeLists.txt
- test/T43.stl.pybind11_include_stl.cli
- test/T43.stl.pybind11_include_stl.config
- test/T43.stl.pybind11_include_stl.hpp
- test/T43.stl.pybind11_include_stl.ref
This PR labels pybind11 objects as builtins. For example `pybind11::dict` and `pybind11::list`.
> STL flag to enable STL bindings

- source/function.cpp
- test/T12.operator.hpp
- test/T12.operator.ref
Support for `operator%` and `operator%=`
It should be worth noting that `%` in C++ and `%` in python are not exact analogs for each other. For example `-7%3` gives `-1` in `C++` and `2` in python. Both are mathematically valid, but python typically also requires the result be positive, it's more of a division remainder. These would only be binding for custom classes / definitions though so I think this is ok to gloss over.
> Add mod support

- source/function.cpp
- test/T12.operator.hpp
- test/T12.operator.ref
Addresses some of the limitations listed in: https://github.com/RosettaCommons/binder/pull/229
> Add support for operators ~ | & ^ << >> |= &= ^= <<= >>=

- documentation/limitations.rst
- source/function.cpp
- test/T12.operator.hpp
- test/T12.operator.ref
This fixes: https://github.com/RosettaCommons/binder/issues/225
It also addresses https://github.com/RosettaCommons/binder/issues/226 by renaming `plus_plus` to `pre_increment` or `post_increment` depending on which is called. It unfortunately does not fix the issue that the post increment operator requires an integer argument. I'm not sure how to fix that. If this is not ok, I can undo this fix and only let this PR address https://github.com/RosettaCommons/binder/issues/225
> Fix unary operators

- documentation/config.rst
- source/class.cpp
- source/config.cpp
- source/config.hpp
- source/context.cpp
- source/type.cpp
- test/CMakeLists.txt
- test/T60.custom_shared.config
- test/T60.custom_shared.hpp
- test/T60.custom_shared.ref
This PR is associated to one of the questions of #214.
The PR adds an option to specify a custom shared pointer class.
The header files can not be included into binder source code as it is unknown at compilation time.
Therefore, the proposed code relies on some string logic to avoid to have a custom shared pointer of a custom shared pointer.
The header(s) associated to the shared pointer should be specified with the `+include` option.
The proposed implementation avoids to create custom shared pointer of std classes.
Finally, the proposed implementation only supports to specify one custom shared pointer class.
Please @lyskov, let me know any comments/modifications that you would like to see in this PR.
> Add custom shared pointer option

- documentation/install.rst
This should hopefully fix
> To statically compile binder, see [With Docker](https://cppbinder.readthedocs.io/en/latest/install.html#building-static).
With
> To statically compile binder, see [Building Statically (Linux only)](https://cppbinder.readthedocs.io/en/latest/install.html#building-static).
> The documentation has a bad reference

- source/class.cpp
- source/config.cpp
- source/config.hpp
- source/enum.cpp
- test/T70.module_local.config
- test/T70.module_local.hpp
- test/T70.module_local.ref
- test/T71.module_local.config
- test/T71.module_local.hpp
- test/T71.module_local.ref
This PR addresses #248 by adding an option to enable `module_local` for a namespace (using `+module_local namespace`) or for all the namespaces(using `+module_local ALL`).
@lyskov
> Add module_local option for namespace to the configuration script

- documentation/limitations.rst
- source/function.cpp
- test/T12.operator.hpp
- test/T12.operator.ref
This is a feature add that also fixes the same bugs that https://github.com/RosettaCommons/binder/pull/237 fixes (as the code introduced in https://github.com/RosettaCommons/binder/pull/237 made it easy to add this feature). It addresses https://github.com/RosettaCommons/binder/issues/226
> Pre post increment ops renamed

- source/enum.cpp
Remove the banned symbols from enum bindings. Note: the banned symbols function notes enums.
Partial solution for #254
> Remove the banned symbols from enum bindings. Note: the banned symbols function notes enums.

- documentation/config.rst
- source/class.cpp
- source/config.cpp
- source/config.hpp
- test/T01.enum.config
- test/T01.enum.hpp
- test/T01.enum.ref.cpp
This commit is based on a larger commit by @charbeljc in https://github.com/RosettaCommons/binder/pull/160 but manually cherry-picking just the "-field" feature.
> Add option to skip binding a field

- build-and-run-tests.py
- build.py
- fix missing parameter `compiler` in call to `build.install_llvm_tool` from `build-and-run-tests.py` (Issue #266)
- add parameter `compiler` to `build.get_cmake_compiler_options`. This  is needed since if the script is imported, then Options is not in global scope.
> Fix build scripts

- documentation/install.rst
Needed to add arm64 instructions.
Added the least recent version of LLVM for arm64 macos (14.0.6) that I could find because I wasn't sure which LLVM versions that this supported; the binder executable builds fine, at least.
> update build instructions for macos

- .clang-format
This makes CLion choke when trying to format
> .clang-format: Remove duplicate key

- CMakeLists.txt
- cmake/Modules/FindPython/Support.cmake
The current `FindPython3.cmake` had a bug in which it failed to find simplified python exes, like `python3`.
Additionally, it was not very good at dealing with systems that had numerous python installations to choose from, like my own; `cmake` >= 3.19 has `FindPython3`, and all the other cmake Modules that you currently have. So, I changed Cmakelists.txt to only include the modules if the cmake version is < 3.19.
> Fix Python finding 

- documentation/limitations.rst
The supported [external operators](https://cppbinder.readthedocs.io/en/latest/limitations.html#external-operators) are ignored in the documentation because a blank line is missing the `code-block` directive.
> Fix external operators in limitations documentation

- .readthedocs.yaml
- documentation/requirements.txt
ReadTheDocs has required an explicit configuration file since a few months ago, see https://docs.readthedocs.io/en/stable/config-file/, and the latest [builds](https://readthedocs.org/projects/cppbinder/builds/) failed because of this. this pull request introduces the configuration file from the log history of the last successful build.
> Add explicit readthedocs config file

- CMakeLists.txt
- source/CMakeLists.txt
- source/main.cpp
Add a command-line option to print binder version.
`binder --version`` will display now
```
binder 1.4.1
LLVM 17.0.6
```
> Add a command-line option to print binder version

- documentation/config.rst
- source/config.hpp
- source/main.cpp
- source/options.cpp
- source/options.hpp
- source/util.cpp
Implementation of an option to skip line numbers in the comments to the generated code.
This option is useful for the following use case:
- the bindings are stored in e.g. git repository and are regenerated from time to time
In this scenario, the input headers might be updated, e.g. the new functions can be added without the updates of the signatures of the binded functions. As a result, if one reruns the binder, the only update of the binded code might be the changes in the line numbers.
To avoid this situation one can remove the line numbers from the comments to the code.
> Implement skip-line-number option

- source/util.cpp
Update util.cpp to avoid compiler warning 
```
/source/util.cpp:138:15: warning: ignoring return value of 'int system(const char*)' declared with attribute 'warn_unused_result' [-Wunused-result]
138 |         system(command_line.c_str());
```
and  trow an error if a directory cannot be created.
> Update util.cpp to avoid compiler warning and  trow an error if a directory cannot be created.

- examples/Dockerfile
The behavior of ARG in multi-stage Dockerfiles is a bit unusual. They are scoped to each stage, so you have to repeat them if you want to use the same variable in multiple stages. *But*, if you set a default value, that default value has to be set before the first stage. [Ref. StackOverflow answer.](https://stackoverflow.com/a/53682110)
The container does not actually build without this change, because the `${CLANG_VERSION}` variable expands to the empty string in the second stage, and then it fails installing `clang--dev`.
> Persist container ARGs across multiple stages

- source/class.cpp
Update class.cpp to avoid compiler warnings
```
source/class.cpp:667:1: warning: multi-line comment [-Wcomment]
667 | // #define PYBIND11_OVERLOAD_INT(ret_type, cname, name, ...) { \
| ^
```
Replaces #283
> Update class.cpp to avoid compiler warnings

- source/class.cpp
- source/context.cpp
Update context.cpp to comply with pybind11 2.0+ docs, i.e.
PYBIND11_DECLARE_HOLDER_TYPE from version 2.0 requires at least 3 arguments otherwise the compillers will issue warnings.
See https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html
```
The first argument of PYBIND11_DECLARE_HOLDER_TYPE() should be a placeholder name that is used as a template parameter of the second argument. Thus, feel free to use any identifier, but use it consistently on both sides; also, don’t use the name of a type that already exists in your codebase.
The macro also accepts a third optional boolean parameter that is set to false by default. 
```
> Update context.cpp to comply with pybind11 2.0+ docs

- source/class.cpp
- source/context.cpp
Update context.cpp to avoid else after return
> Update context.cpp to avoid else after return

- source/class.cpp
Update class.cpp to make code compatible with MSVC.
Should solve #298
> Update class.cpp to make code compatible with MSVC

- source/function.hpp
I found this error when trying to build `binder` with MSVC. Relates to #20, #59.
> Fix MSVC error on unknown identifier uint in `function.hpp`

- build.py
Python 3.12 doesn't have `imp`, and this file doesn't seem to actually use it.
> Remove import of removed, unused Python modules

- build-and-run-tests.py
- build.py
This PR updates Binder to work on Ubuntu 24.04, with its GCC 13.
It also implements the compiler-version-dependent LLVM version selection logic that the build scripts wanted, and adds an `--llvm-version` command line flag to them to override it.
It includes LLVM 14.0.5, which will be automatically selected for GCC 13 or newer, since it's the oldest LLVM I could find that can build on GCC 13 and understand GCC 13's STL headers.
I had to change how the LLVM tarballs are extracted to not lose the `cmake` directory that LLVM 14.0.5 needs next to its source directory to build. I added some version tracking for this directory, which will involve redownloading LLVM if it needs to change versions.
> Support Ubuntu 24.04 and LLVM 14.0.5; automatically select LLVM version based on compiler version

- documentation/install.rst
Included is a update to the llvm path in the final build command. This is necessary because while LLVM 6.0.1 originally used a multi-repo structure, the llvmorg-6.0.1 tag has since been retroactively added to the monorepo. As a result, the build must now target the llvm/ subdirectory inside llvm-project.
> Ensure Binder compatibility with LLVM monorepo structure

- .github/workflows/main.yml
`macos-latest` corresponds to the arm64 runners, the "latest" version of the x86 runners is `macos-13`.
> Fix MacOSX CI
